import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

import { MantineProvider } from '@mantine/core';
import { Title, Text, Container, Stack } from '@mantine/core';

import ConditionsCountChartCard from './components/ConditionsCountChartCard';
import { APP_CONFIG } from './config';

export default function App() {
  return (
    <MantineProvider>
      <Container my="xl">
        <Stack justify="center" align="center" mb="xl">
          <Title>{APP_CONFIG.TITLE}</Title>
          <Text>
            A small dashboard exploring synthetic patient data generated by
            Synthea
          </Text>
        </Stack>

        <ConditionsCountChartCard />
      </Container>
    </MantineProvider>
  );
}
