import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

import { MantineProvider } from '@mantine/core';
import { Title, Text } from '@mantine/core';

import ConditionsCountChartCard from './components/ConditionsCountChartCard';

export default function App() {
  return (
    <MantineProvider>
      <div>
        <Title>Synthea patient insights</Title>
        <Text>
          A small dashboard exploring sythetic patient data generated by Synthea
        </Text>

        <ConditionsCountChartCard />
      </div>
    </MantineProvider>
  );
}
