import { useState, useEffect } from 'react';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

import { MantineProvider } from '@mantine/core';
import { Title, Text, Loader } from '@mantine/core';
import { BarChart } from '@mantine/charts';

import { fetchConditionCounts } from './services/syntheaApiService';
import { type PivotedConditionCounts } from './utils/types';
import {
  pivotByCondition,
  sortPivotedConditionCountsByGender,
  limitTopNConditions,
} from './utils/transforms';

const LIMIT_TOP_N_CONDITIONS = 10;

export default function App() {
  const [conditionCounts, setConditionCounts] = useState<
    PivotedConditionCounts[] | null
  >(null);

  const baseUrl = 'http://localhost:8080';

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetchConditionCounts(baseUrl);

      if (data) {
        const transformedData = limitTopNConditions(
          sortPivotedConditionCountsByGender(pivotByCondition(data)),
          LIMIT_TOP_N_CONDITIONS,
        );
        setConditionCounts(transformedData);
      } else {
        console.warn('No condition counts data received from the API.');
      }
    };

    fetchData();
  }, []);

  console.log('transformed conditionCounts:', conditionCounts);

  return (
    <MantineProvider>
      <div>
        <Title>Synthea patient insights</Title>
        <Text>
          A small dashboard exploring sythetic patient data generated by Synthea
        </Text>
        <Title order={2} mt="md">
          Top conditions by gender
        </Title>
        <Text>
          The 10 most common conditions overall, broken down by patient gender.
        </Text>
        {conditionCounts ? (
          <BarChart
            data={conditionCounts}
            dataKey="condition_description"
            series={[
              { name: 'male', color: 'blue.6' },
              { name: 'female', color: 'red.6' },
            ]}
            orientation="vertical"
            h={400}
            w={600}
          />
        ) : (
          <Loader
            size="xl"
            type="dots"
            color="blue"
            style={{ marginTop: '20px' }}
          />
        )}
      </div>
    </MantineProvider>
  );
}
